# For more on theme configuration check:
# https://github.com/pages-themes/minimal?tab=readme-ov-file
#
# For favicon and logo check:
# https://redketchup.io/favicon-generator
#
# Colors: #311B92 / #F57F17
# Font: Ubuntu

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Learning by Teaching
description: My notes and everything else!
logo: /assets/img/logo.png
show_downloads: true
