# For more on theme configuration check:
# https://github.com/pages-themes/minimal?tab=readme-ov-file

# theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Learning by Teaching
description: My notes and everything else!
show_downloads: true
google_analytics: null
