name = "kiln-model"
version = "0.1.0"
license = "license"
author = "Walter Dal'Maz Silva"
maintainer = "walter.dalmazsilva@gmail.com"
copyright = "Copyright 2025, Walter Dal'Maz Silva"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
